name: Create GPT Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y parted

      - name: Create GPT Image
        run: |
          # 1GBの空のイメージファイルを作成
          dd if=/dev/zero of=custom_gpt.img bs=1M count=1024

          # ループバックデバイスに接続
          LOOP_DEV=$(sudo losetup --show -f custom_gpt.img)

          # パーティションテーブルを作成
          sudo parted ${LOOP_DEV} mklabel gpt

          # パーティションを作成（例としていくつかのパーティションを作成）
          sudo parted ${LOOP_DEV} mkpart primary ext4 1MiB 128MiB
          sudo parted ${LOOP_DEV} name 1 sd_boot

          sudo parted ${LOOP_DEV} mkpart primary ext4 129MiB 256MiB
          sudo parted ${LOOP_DEV} name 2 sd_logo

          sudo parted ${LOOP_DEV} mkpart primary ext4 257MiB 384MiB
          sudo parted ${LOOP_DEV} name 3 sd_dtbo

          sudo parted ${LOOP_DEV} mkpart primary ext4 385MiB 512MiB
          sudo parted ${LOOP_DEV} name 4 sd_tee1

          sudo parted ${LOOP_DEV} mkpart primary ext4 513MiB 640MiB
          sudo parted ${LOOP_DEV} name 5 sd_tee2

          sudo parted ${LOOP_DEV} mkpart primary ext4 641MiB 768MiB
          sudo parted ${LOOP_DEV} name 6 sd_vbmeta

          sudo parted ${LOOP_DEV} mkpart primary ext4 769MiB 896MiB
          sudo parted ${LOOP_DEV} name 7 sd_nvdata

          sudo parted ${LOOP_DEV} mkpart primary ext4 897MiB 1024MiB
          sudo parted ${LOOP_DEV} name 8 sd_nvcfg

          sudo parted ${LOOP_DEV} mkpart primary ext4 1025MiB 1152MiB
          sudo parted ${LOOP_DEV} name 9 sd_nvram

          sudo parted ${LOOP_DEV} mkpart primary ext4 1153MiB 1280MiB
          sudo parted ${LOOP_DEV} name 10 sd_expdb

          # ループバックデバイスをデタッチ
          sudo losetup -d ${LOOP_DEV}

      - name: Upload GPT Image
        uses: actions/upload-artifact@v3
        with:
          name: custom_gpt.img
          path: custom_gpt.img
