name: Create GPT Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y parted gdisk

      - name: Create GPT Image
        run: |
          # 1GBの空のイメージファイルを作成
          dd if=/dev/zero of=custom_gpt.img bs=1M count=1024

          # ループバックデバイスに接続
          LOOP_DEV=$(losetup --show -f custom_gpt.img)

          # パーティションテーブルを作成
          parted ${LOOP_DEV} mklabel gpt

          # パーティションを作成（例としていくつかのパーティションを作成）
          sgdisk -n 1:0x10000:0x17fff -t 1:8300 -c 1:"sd_boot" ${LOOP_DEV}
          sgdisk -n 2:0x18000:0x1bfff -t 2:8300 -c 2:"sd_logo" ${LOOP_DEV}
          sgdisk -n 3:0x1c000:0x1ffff -t 3:8300 -c 3:"sd_dtbo" ${LOOP_DEV}
          sgdisk -n 4:0x20000:0x227ff -t 4:8300 -c 4:"sd_tee1" ${LOOP_DEV}
          sgdisk -n 5:0x22800:0x24fff -t 5:8300 -c 5:"sd_tee2" ${LOOP_DEV}
          sgdisk -n 6:0x25000:0x29fff -t 6:8300 -c 6:"sd_vbmeta" ${LOOP_DEV}
          sgdisk -n 7:0x2aa00:0x3a9ff -t 7:8300 -c 7:"sd_nvdata" ${LOOP_DEV}
          sgdisk -n 8:0x3aa00:0x3e9ff -t 8:8300 -c 8:"sd_nvcfg" ${LOOP_DEV}
          sgdisk -n 9:0x3ea00:0x411ff -t 9:8300 -c 9:"sd_nvram" ${LOOP_DEV}
          sgdisk -n 10:0x41200:0x461ff -t 10:8300 -c 10:"sd_expdb" ${LOOP_DEV}

          # ループバックデバイスをデタッチ
          losetup -d ${LOOP_DEV}

      - name: Upload GPT Image
        uses: actions/upload-artifact@v3
        with:
          name: custom_gpt.img
          path: custom_gpt.img
